spring:
  application:
    name: shiori-user-service
  config:
    import:
      - optional:nacos:${spring.application.name}-base.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
      - optional:nacos:${spring.application.name}-secret.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
      - optional:nacos:shiori-security-base.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
      - optional:nacos:shiori-security-secret.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos:8848}
      config:
        server-addr: ${NACOS_ADDR:nacos:8848}
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}

server:
  port: 8081

user:
  authz:
    snapshot-ttl-seconds: ${USER_AUTHZ_SNAPSHOT_TTL_SECONDS:30}
    event:
      enabled: ${USER_AUTHZ_EVENT_ENABLED:true}
      redis-channel: ${USER_AUTHZ_EVENT_REDIS_CHANNEL:shiori.authz.user.changed}
  security:
    login-fail-lock-threshold: ${USER_LOGIN_FAIL_LOCK_THRESHOLD:5}
    lock-minutes: ${USER_LOCK_MINUTES:15}
  payment-client:
    service-base-url: ${USER_PAYMENT_SERVICE_BASE_URL:http://shiori-payment-service}
    internal-token: ${ORDER_PAYMENT_INTERNAL_TOKEN:}
  outbox:
    enabled: ${USER_OUTBOX_ENABLED:true}
  mq:
    event-exchange: ${USER_EVENT_EXCHANGE:shiori.user.event}
    user-status-changed-routing-key: ${USER_STATUS_CHANGED_ROUTING_KEY:user.status.changed}
    user-role-changed-routing-key: ${USER_ROLE_CHANGED_ROUTING_KEY:user.role.changed}
    user-password-reset-routing-key: ${USER_PASSWORD_RESET_ROUTING_KEY:user.password.reset}
    user-permission-override-changed-routing-key: ${USER_PERMISSION_OVERRIDE_CHANGED_ROUTING_KEY:user.permission-override.changed}
    user-role-bindings-changed-routing-key: ${USER_ROLE_BINDINGS_CHANGED_ROUTING_KEY:user.role-bindings.changed}
  avatar:
    storage:
      enabled: ${USER_AVATAR_STORAGE_ENABLED:true}
      endpoint: ${USER_AVATAR_STORAGE_ENDPOINT:http://localhost:9000}
      region: ${USER_AVATAR_STORAGE_REGION:us-east-1}
      access-key: ${USER_AVATAR_STORAGE_ACCESS_KEY:shiori}
      secret-key: ${USER_AVATAR_STORAGE_SECRET_KEY:shiori-minio-secret}
      bucket: ${USER_AVATAR_STORAGE_BUCKET:shiori-user-avatar}
      path-style-access: ${USER_AVATAR_STORAGE_PATH_STYLE:true}
      max-file-size-bytes: ${USER_AVATAR_MAX_FILE_SIZE_BYTES:2097152}
      public-path-prefix: ${USER_AVATAR_PUBLIC_PATH_PREFIX:/api/user/media/avatar/}
