spring:
  application:
    name: shiori-order-service
  config:
    import:
      - optional:nacos:${spring.application.name}-base.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
      - optional:nacos:${spring.application.name}-secret.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
      - optional:nacos:shiori-security-base.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
      - optional:nacos:shiori-security-secret.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos:8848}
      config:
        server-addr: ${NACOS_ADDR:nacos:8848}
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}

server:
  port: 8083

order:
  timeout-minutes: ${ORDER_TIMEOUT_MINUTES:15}
  product-client:
    service-base-url: ${ORDER_PRODUCT_SERVICE_BASE_URL:http://shiori-product-service}
  payment-client:
    service-base-url: ${ORDER_PAYMENT_SERVICE_BASE_URL:http://shiori-payment-service}
  notify-client:
    service-base-url: ${ORDER_NOTIFY_SERVICE_BASE_URL:http://shiori-notify}
  outbox:
    enabled: ${ORDER_OUTBOX_ENABLED:true}
    relay-fixed-delay-ms: ${ORDER_OUTBOX_RELAY_FIXED_DELAY_MS:3000}
    relay-batch-size: ${ORDER_OUTBOX_RELAY_BATCH_SIZE:100}
    max-backoff-seconds: ${ORDER_OUTBOX_MAX_BACKOFF_SECONDS:300}
  mq:
    enabled: ${ORDER_MQ_ENABLED:true}
    event-exchange: ${ORDER_EVENT_EXCHANGE:shiori.order.event}
    order-created-routing-key: ${ORDER_CREATED_ROUTING_KEY:order.created}
    order-paid-routing-key: ${ORDER_PAID_ROUTING_KEY:order.paid}
    order-canceled-routing-key: ${ORDER_CANCELED_ROUTING_KEY:order.canceled}
    delay-exchange: ${ORDER_DELAY_EXCHANGE:shiori.order.delay}
    delay-routing-key: ${ORDER_DELAY_ROUTING_KEY:order.timeout}
    timeout-dlx-exchange: ${ORDER_TIMEOUT_DLX_EXCHANGE:shiori.order.timeout.dlx}
    timeout-delay-queue: ${ORDER_TIMEOUT_DELAY_QUEUE:q.order.timeout.delay}
    timeout-consume-queue: ${ORDER_TIMEOUT_CONSUME_QUEUE:q.order.timeout.consume}
    timeout-ttl-ms: ${ORDER_TIMEOUT_TTL_MS:900000}
