ALTER TABLE u_user
    ADD COLUMN gender TINYINT NOT NULL DEFAULT 0 COMMENT '0=UNKNOWN,1=MALE,2=FEMALE,9=PRIVATE' AFTER avatar_url,
    ADD COLUMN birth_date DATE NULL AFTER gender,
    ADD COLUMN bio VARCHAR(280) NULL AFTER birth_date;
