spring:
  application:
    name: shiori-product-service
  config:
    import:
      - optional:nacos:${spring.application.name}-base.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
      - optional:nacos:${spring.application.name}-secret.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
      - optional:nacos:shiori-security-base.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
      - optional:nacos:shiori-security-secret.yml?group=${NACOS_CONFIG_GROUP:SHIORI_DEV_DOCKER}&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos:8848}
      config:
        server-addr: ${NACOS_ADDR:nacos:8848}
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}

server:
  port: 8082

product:
  outbox:
    enabled: ${PRODUCT_OUTBOX_ENABLED:true}
  mq:
    event-exchange: ${PRODUCT_EVENT_EXCHANGE:shiori.product.event}
    product-published-routing-key: ${PRODUCT_PUBLISHED_ROUTING_KEY:product.published}
