global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: shiori-gateway-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - shiori-gateway-service:8080

  - job_name: shiori-user-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - shiori-user-service:8081

  - job_name: shiori-product-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - shiori-product-service:8082

  - job_name: shiori-order-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - shiori-order-service:8083

  - job_name: shiori-payment-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - shiori-payment-service:8084

  - job_name: shiori-notify-metrics
    metrics_path: /metrics
    static_configs:
      - targets:
          - shiori-notify-service:8090
