#!/bin/sh
set -eu

require_env() {
  key="$1"
  eval "value=\${${key}:-}"
  if [ -z "${value}" ]; then
    echo "[mysql-init][ERROR] missing env: ${key}" >&2
    exit 1
  fi
}

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

require_env MYSQL_ROOT_PASSWORD
require_env USER_DB_USERNAME
require_env USER_DB_PASSWORD
require_env PRODUCT_DB_USERNAME
require_env PRODUCT_DB_PASSWORD
require_env ORDER_DB_USERNAME
require_env ORDER_DB_PASSWORD
require_env PAYMENT_DB_USERNAME
require_env PAYMENT_DB_PASSWORD
require_env NOTIFY_DB_USERNAME
require_env NOTIFY_DB_PASSWORD
require_env MYSQL_OPS_USERNAME
require_env MYSQL_OPS_PASSWORD

USER_DB_USERNAME_ESC="$(sql_escape "${USER_DB_USERNAME}")"
USER_DB_PASSWORD_ESC="$(sql_escape "${USER_DB_PASSWORD}")"
PRODUCT_DB_USERNAME_ESC="$(sql_escape "${PRODUCT_DB_USERNAME}")"
PRODUCT_DB_PASSWORD_ESC="$(sql_escape "${PRODUCT_DB_PASSWORD}")"
ORDER_DB_USERNAME_ESC="$(sql_escape "${ORDER_DB_USERNAME}")"
ORDER_DB_PASSWORD_ESC="$(sql_escape "${ORDER_DB_PASSWORD}")"
PAYMENT_DB_USERNAME_ESC="$(sql_escape "${PAYMENT_DB_USERNAME}")"
PAYMENT_DB_PASSWORD_ESC="$(sql_escape "${PAYMENT_DB_PASSWORD}")"
NOTIFY_DB_USERNAME_ESC="$(sql_escape "${NOTIFY_DB_USERNAME}")"
NOTIFY_DB_PASSWORD_ESC="$(sql_escape "${NOTIFY_DB_PASSWORD}")"
MYSQL_OPS_USERNAME_ESC="$(sql_escape "${MYSQL_OPS_USERNAME}")"
MYSQL_OPS_PASSWORD_ESC="$(sql_escape "${MYSQL_OPS_PASSWORD}")"

mysql --protocol=socket -uroot "-p${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`shiori_user\`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS \`shiori_product\`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS \`shiori_order\`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS \`shiori_payment\`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS \`shiori_notify\`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS '${USER_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${USER_DB_PASSWORD_ESC}';
ALTER USER '${USER_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${USER_DB_PASSWORD_ESC}';
GRANT ALL PRIVILEGES ON \`shiori_user\`.* TO '${USER_DB_USERNAME_ESC}'@'%';

CREATE USER IF NOT EXISTS '${PRODUCT_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${PRODUCT_DB_PASSWORD_ESC}';
ALTER USER '${PRODUCT_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${PRODUCT_DB_PASSWORD_ESC}';
GRANT ALL PRIVILEGES ON \`shiori_product\`.* TO '${PRODUCT_DB_USERNAME_ESC}'@'%';

CREATE USER IF NOT EXISTS '${ORDER_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${ORDER_DB_PASSWORD_ESC}';
ALTER USER '${ORDER_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${ORDER_DB_PASSWORD_ESC}';
GRANT ALL PRIVILEGES ON \`shiori_order\`.* TO '${ORDER_DB_USERNAME_ESC}'@'%';

CREATE USER IF NOT EXISTS '${PAYMENT_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${PAYMENT_DB_PASSWORD_ESC}';
ALTER USER '${PAYMENT_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${PAYMENT_DB_PASSWORD_ESC}';
GRANT ALL PRIVILEGES ON \`shiori_payment\`.* TO '${PAYMENT_DB_USERNAME_ESC}'@'%';

CREATE USER IF NOT EXISTS '${NOTIFY_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${NOTIFY_DB_PASSWORD_ESC}';
ALTER USER '${NOTIFY_DB_USERNAME_ESC}'@'%' IDENTIFIED BY '${NOTIFY_DB_PASSWORD_ESC}';
GRANT ALL PRIVILEGES ON \`shiori_notify\`.* TO '${NOTIFY_DB_USERNAME_ESC}'@'%';

CREATE USER IF NOT EXISTS '${MYSQL_OPS_USERNAME_ESC}'@'%' IDENTIFIED BY '${MYSQL_OPS_PASSWORD_ESC}';
ALTER USER '${MYSQL_OPS_USERNAME_ESC}'@'%' IDENTIFIED BY '${MYSQL_OPS_PASSWORD_ESC}';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`shiori_user\`.* TO '${MYSQL_OPS_USERNAME_ESC}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`shiori_product\`.* TO '${MYSQL_OPS_USERNAME_ESC}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`shiori_order\`.* TO '${MYSQL_OPS_USERNAME_ESC}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`shiori_payment\`.* TO '${MYSQL_OPS_USERNAME_ESC}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON \`shiori_notify\`.* TO '${MYSQL_OPS_USERNAME_ESC}'@'%';

FLUSH PRIVILEGES;
SQL
